#!/bin/bash
set -e

STAGE="dev"
while [[ $# -gt 0 ]]; do
  case $1 in
    --stage) STAGE="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

STACK_NAME="SimpleChatbot-${STAGE}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../frontend/.env.${STAGE}"

echo "Reading outputs from ${STACK_NAME}..."

get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

WEBSITE_URL=$(get_output "WebsiteUrl")
USER_POOL_ID=$(get_output "UserPoolId")
USER_POOL_CLIENT_ID=$(get_output "UserPoolClientId")

if [[ -z "$WEBSITE_URL" || -z "$USER_POOL_ID" || -z "$USER_POOL_CLIENT_ID" ]]; then
  echo "Error: one or more required stack outputs are missing." >&2
  exit 1
fi

# VITE_API_GATEWAY_URL points to CloudFront — /api/* is proxied to API Gateway.
# This avoids CORS entirely since frontend and API share the same origin.
cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate_env.sh — do not edit manually
VITE_API_GATEWAY_URL=${WEBSITE_URL%/}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
EOF

echo "Written: $ENV_FILE"
